<?php
// ═══════════════════════════════════════════════════════════
//  PUBLIC QR VERIFICATION PAGE
//  GET verify_qr.php?ref=<reference>&token=<verify_token>
//
//  No login required — this is the page a phone camera opens when it
//  scans a QR code generated by track_application.php's QR Code
//  Verification step. It never trusts anything encoded in the QR
//  image itself beyond the reference + token pair; everything shown
//  below (applicant, status, signed date) comes from a fresh lookup
//  against the `qr_verifications` table. If the pair doesn't match a
//  row, the record is reported INVALID / NOT FOUND — a copied or
//  hand-edited QR code cannot be made to pass.
// ═══════════════════════════════════════════════════════════

$dbFile = __DIR__ . '/connection.php';
if (!file_exists($dbFile)) {
    $dbFile = __DIR__ . '/../connection.php';
}

$valid    = false;
$record   = null;
$errorMsg = null;

// Friendly display names, matching the SERVICES list in track_application.php.
$SERVICE_NAMES = [
    'tesda_'   => 'TESDA Enrollment',
    'bir_'     => 'BIR TIN Registration',
    'dswd_'    => 'DSWD Assistance',
    'vid_'     => 'Valid ID Application',
    'smf_'     => 'SM Foundation Scholarship',
    'ched_'    => 'CHED Scholarship',
    'comelec_' => 'COMELEC Voter Registration',
    'psa_'     => 'PSA Certificate Request',
    'lgu_'     => 'LGU Online Services',
    'lto_'     => "LTO Driver's License",
    'aha_'     => 'AHA Learning Center',
];

// For the DB-backed services, re-check the live status column instead
// of trusting whatever was last saved into qr_verifications — so a
// status that changed (e.g. later rejected/revoked) after the QR was
// generated is reflected immediately, not just at generation time.
$LIVE_STATUS_TABLES = [
    'vid_'   => 'validid',
    'tesda_' => 'tesda',
    'ched_'  => 'ched',
];

if (!file_exists($dbFile)) {
    $errorMsg = 'Database connection unavailable.';
} else {
    require_once $dbFile;

    if (!isset($Connection)) {
        $errorMsg = 'Database connection unavailable.';
    } else {
        $ref   = trim($_GET['ref'] ?? '');
        $token = trim($_GET['token'] ?? '');

        if ($ref === '' || $token === '') {
            $errorMsg = 'Missing reference or verification token.';
        } else {
            $refEsc   = mysqli_real_escape_string($Connection, $ref);
            $tokenEsc = mysqli_real_escape_string($Connection, $token);

            $res = mysqli_query(
                $Connection,
                "SELECT * FROM qr_verifications WHERE reference = '$refEsc' AND verify_token = '$tokenEsc' LIMIT 1"
            );

            if ($res && $row = mysqli_fetch_assoc($res)) {
                $valid  = true;
                $record = $row;

                if (isset($LIVE_STATUS_TABLES[$row['service_prefix']])) {
                    $table  = $LIVE_STATUS_TABLES[$row['service_prefix']];
                    $liveRes = mysqli_query(
                        $Connection,
                        "SELECT appstatus FROM `$table` WHERE reference = '$refEsc' LIMIT 1"
                    );
                    if ($liveRes && $liveRow = mysqli_fetch_assoc($liveRes)) {
                        if (!empty($liveRow['appstatus'])) {
                            $record['status'] = $liveRow['appstatus'];
                        }
                    }
                }
            }
        }
    }
}

function h($s) { return htmlspecialchars((string) $s, ENT_QUOTES); }
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document Verification — E-Gov Portal</title>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<style>
:root {
    --primary-color: #004aad;
    --secondary-color: #0077ff;
    --accent-color: #ffd700;
    --text-dark: #333333;
    --text-light: #666666;
    --bg-light: #f8f9fa;
    --white: #ffffff;
    --success: #2e7d32;
    --danger: #c62828;
}
* { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Poppins', sans-serif; }
body {
    background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    min-height: 100vh;
    display: flex; align-items: center; justify-content: center;
    padding: 24px;
}
.verify-card {
    background: var(--white);
    border-radius: 20px;
    max-width: 440px; width: 100%;
    box-shadow: 0 20px 50px rgba(0,0,0,0.25);
    overflow: hidden;
}
.verify-banner {
    padding: 30px 24px 24px;
    text-align: center; color: white;
}
.verify-banner.valid   { background: linear-gradient(135deg, #2e7d32, #43a047); }
.verify-banner.invalid { background: linear-gradient(135deg, #c62828, #e53935); }
.verify-banner i { font-size: 44px; margin-bottom: 10px; display: block; }
.verify-banner h1 { font-size: 20px; font-weight: 700; letter-spacing: 0.3px; }
.verify-banner p { font-size: 13px; opacity: 0.92; margin-top: 4px; }

.verify-body { padding: 22px 24px 26px; }
.verify-row {
    display: flex; justify-content: space-between; gap: 12px;
    padding: 10px 0; border-bottom: 1px solid #eef0f8;
    font-size: 13.5px;
}
.verify-row:last-child { border-bottom: none; }
.verify-row .label { color: var(--text-light); font-weight: 600; }
.verify-row .value { color: var(--text-dark); font-weight: 600; text-align: right; }

.verify-footnote {
    margin-top: 20px; padding-top: 16px;
    border-top: 1px dashed #e0e6f2;
    font-size: 11.5px; color: var(--text-light); text-align: center;
    line-height: 1.5;
}
</style>
</head>
<body>
<div class="verify-card">
<?php if ($valid): ?>
    <div class="verify-banner valid">
        <i class="fas fa-circle-check"></i>
        <h1>VALID DOCUMENT</h1>
        <p>This application record is authentic and on file.</p>
    </div>
    <div class="verify-body">
        <div class="verify-row"><span class="label">Service</span><span class="value"><?= h($SERVICE_NAMES[$record['service_prefix']] ?? $record['service_prefix']) ?></span></div>
        <div class="verify-row"><span class="label">Reference</span><span class="value"><?= h($record['reference']) ?></span></div>
        <div class="verify-row"><span class="label">Applicant</span><span class="value"><?= h($record['applicant_name']) ?></span></div>
        <div class="verify-row"><span class="label">Status</span><span class="value"><?= h($record['status']) ?></span></div>
        <div class="verify-row"><span class="label">Signature Code</span><span class="value"><?= h($record['signature_code']) ?></span></div>
        <div class="verify-row"><span class="label">Signed</span><span class="value"><?= h(date('M j, Y g:i A', strtotime($record['signed_at']))) ?></span></div>
        <div class="verify-footnote">Verified against the E-Gov Portal database in real time. This page does not trust the QR image itself — only the matching database record.</div>
    </div>
<?php else: ?>
    <div class="verify-banner invalid">
        <i class="fas fa-circle-xmark"></i>
        <h1>INVALID / NOT FOUND</h1>
        <p><?= h($errorMsg ?: 'No matching record exists for this QR code.') ?></p>
    </div>
    <div class="verify-body">
        <div class="verify-footnote">This QR code could not be matched to any record in the E-Gov Portal database. It may be fake, altered, expired, or copied from elsewhere.</div>
    </div>
<?php endif; ?>
</div>
</body>
</html>